### ISSUE TITLE
rfe: markup to ignore lines

### ISSUE THREAD

**Issue by andreas-kupries** [apnadkarni/tcl9-migrate#5]
especially with STRINGISINT I believe it will be a good thing to be able to mark a line as `ignore it` and not have the tool report it.

because even if something is changed around the line to deal with the 8/9 differences the check itself is likely unchanged and thus keeps getting reported.

so I would like to tell/force the tool to not report.

The tooling in Critcl looks for `OK tcl9` to know when not to report a line.

**Comment by apnadkarni** [comment]
See the README for ignoring false positives.
