### ISSUE TITLE
rfe: add check for glob without -nocomplain

### ISSUE THREAD

**Issue by chpock** [apnadkarni/tcl9-migrate#7]
According to https://core.tcl-lang.org/tcl/wiki?name=Migrating+scripts+to+Tcl+9 :
> In Tcl 9, the glob command returns an empty list if no files match the specified pattern instead rasiing an error. This is true irrespective of the presence of the -nocomplain option which is still accepted but has no significance. Any scripts that expect an error to be raised in such cases will need to be modified to check for an empty list instead.

This can lead to a hidden error if the application logic expects an error return code when no matching file is found.

Please consider adding check for `glob` command. If `glob` is wrapped in `catch`/`try`, there is a very good chance that this code will work differently in tcl8 and tcl9.

However, I think all `glob` commands without `-nocomplain` should be under suspicion. Perhaps the error return code is expected not from a procedure executing the `glob` command, but from procedures that are higher up the stack.

For example:
```
proc load_modules_from_dir { dir } {
    foreach module_file [glob -directory $dir *.module] {
        load_module $module_file
    }
}

proc init { home } {
    if { [catch { load_modules_from_dir [file join $dir "myapp"] } err] } {
        puts "No modules or an error occurred while loading modules: $err"
        # do something when there are no modules
    }
}
```

**Comment by apnadkarni** [comment]
I understand the need and not hard to implement but I'm concerned there will be too many false positives. In particular, in code ported to Tcl 9 without needing backward compatibility to Tcl 8, users may intentionally remove the -nocomplain option clutter.

**Comment by apnadkarni** [comment]
Added the check as a note level message.
