### ISSUE TITLE
Typo in handling the variable command

### ISSUE THREAD

**Issue by hvxl** [apnadkarni/tcl9-migrate#8]
I ran into a typo in the handling of the "variable" command. The same typo is also present in the "global" leg of the switch.  
While making changes in that area anyway, I also added a check to prevent that a misused "global" inside a "namespace eval" would hide the fact that the global variable is not in scope. (Related to issue #4.)

Here's a patch with the fix: [variable.patch](https://github.com/user-attachments/files/16998780/variable.patch.txt)

**Comment by apnadkarni** [comment]
Oops. Thanks.
